Repository blakeblackshear/frigate-hass-integration, pull requests merged in 2022-07, with the labels that each got.

#296 Add service to 'favorite' an event
  custom_components/frigate/camera.py
  custom_components/frigate/const.py
  custom_components/frigate/services.yaml
  tests/test_camera.py
Labels: enhancement

#298 Bump version to 3.0.0-rc.3 .
  custom_components/frigate/manifest.json
Labels: build

#299 Remove the HTTP view for recordings API (WS still available)
  custom_components/frigate/__init__.py
  custom_components/frigate/views.py
  tests/test_views.py
Labels: removal

#301 Allow favorite_event to be configured from UI
  custom_components/frigate/camera.py
  custom_components/frigate/const.py
  custom_components/frigate/services.yaml
  tests/test_camera.py
Labels: enhancement

#300 Improve devcontainer experience (e.g. adds python debugging, improves port forwarding)
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/home_assistant_run.sh
  .devcontainer/post_create.sh
  .devcontainer/set_dot_env.sh
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  docker-compose.yml
Labels: testing

#303 Upgrade Python from 3.9 to 3.10
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/build.yaml
Labels: build

#302 Use debugpy hass integration in devcontainer
  .devcontainer/config/configuration.yaml
  .devcontainer/config/specific_configuration.yaml
  .devcontainer/devcontainer.json
  .devcontainer/follow_ha.sh
  .devcontainer/home_assistant_run.sh
  .devcontainer/wait_port.sh
  .vscode/launch.json
  .vscode/tasks.json
  docker-compose.yml
Labels: testing

#305 Set up dependabot for Actions
  .github/dependabot.yml
Labels: build

#306 Upgrade Home Assistant to 2022.7
  requirements.txt
  requirements_dev.txt
  tests/test_media_source.py
Labels: build

#309 Use new-style HA entity naming (renames sensor.frigate_detection_fps, sensor.frigate_[detector] entities)
  custom_components/frigate/__init__.py
  custom_components/frigate/binary_sensor.py
  custom_components/frigate/camera.py
  custom_components/frigate/sensor.py
  custom_components/frigate/switch.py
  custom_components/frigate/update.py
  tests/__init__.py
Labels: breaking

#313 FEAT: Add support for coral temp sensor entities
  custom_components/frigate/const.py
  custom_components/frigate/sensor.py
  tests/__init__.py
  tests/test_sensor.py
Labels: enhancement

#315 Add icon for motorcycle entities
  custom_components/frigate/const.py
  custom_components/frigate/sensor.py
  tests/test_sensor.py
Labels: enhancement

#316 FEAT: Allow threshold and contour_area to be set from Home Assistant
  custom_components/frigate/const.py
  custom_components/frigate/number.py
  tests/__init__.py
  tests/test_number.py
Labels: enhancement

#321 Avoid decoding json when proxying over ws
  custom_components/frigate/api.py
  custom_components/frigate/ws_api.py
  tests/test_ws_api.py
Labels: performance

#323 Use iter_any() instead of iter_chunked()
  custom_components/frigate/views.py
Labels: performance
