Repository blakeblackshear/frigate-hass-integration, pull requests merged in 2022-01, with the labels that each got.

#196 Update the HACS github action
  .github/workflows/build.yaml
Labels: build

#195 Only add camera objects to zones if that zone defines that object
  custom_components/frigate/__init__.py
Labels: bug

#201 Support more states for main camera entity
  custom_components/frigate/camera.py
  tests/test_camera.py
Labels: enhancement

#202 Bump version to v2.2.1 .
  custom_components/frigate/manifest.json
Labels: build

#204 use retain=False for command topic
  custom_components/frigate/switch.py
  tests/test_switch.py
Labels: bug
