Repository blakeblackshear/frigate-hass-integration, pull requests merged in 2022-02, with the labels that each got.

#213 MQTT change to support >= HA 2022.3.0
  custom_components/frigate/__init__.py
Labels: bug

#214 Bump to v2.2.2
  custom_components/frigate/manifest.json
Labels: build

#216 Add Brazilian Portuguese translations
  custom_components/frigate/translations/pt_br.json
Labels: documentation

#221 Rename Brazilian Portuguese Translation
  custom_components/frigate/translations/pt-BR.json
Labels: documentation
