Repository blakeblackshear/frigate-hass-integration, pull requests merged in 2022-08, with the labels that each got.

#322 Fetch thumbnails over http instead of using base64 embedded thumbnails
  custom_components/frigate/__init__.py
  custom_components/frigate/api.py
  custom_components/frigate/media_source.py
  custom_components/frigate/views.py
  tests/fixtures/events_front_door.json
  tests/test_media_source.py
  tests/test_views.py
Labels: performance

#326 Remove "static/" from ThumbnailsProxyView path
  custom_components/frigate/media_source.py
  custom_components/frigate/views.py
  tests/test_media_source.py
  tests/test_views.py
Labels: performance

#329 Restore JSON decode for ws_api
  custom_components/frigate/ws_api.py
  tests/test_ws_api.py
Labels: bug

#330 Revert "Restore JSON decode for ws_api (#329)"
  custom_components/frigate/ws_api.py
  tests/test_ws_api.py
Labels: performance

#333 Don't proxy authSig parameter unless necessary
  custom_components/frigate/views.py
Labels: performance

#331 Update VodSegmentProxyView to allow mp4/m4s files
  custom_components/frigate/views.py
Labels: enhancement

#169 Allow setting an expiration time for unauthenticated notification events
  custom_components/frigate/config_flow.py
  custom_components/frigate/const.py
  custom_components/frigate/translations/en.json
  custom_components/frigate/views.py
  tests/test_config_flow.py
  tests/test_views.py
Labels: enhancement

#317 Add icons for bicycle, cow, and horse, and change car and person icons
  custom_components/frigate/const.py
  custom_components/frigate/sensor.py
  tests/test_sensor.py
Labels: enhancement
