Repository blakeblackshear/frigate-hass-integration, pull requests merged in 2022-05, with the labels that each got.

#254 Add diagnostics
  custom_components/frigate/const.py
  custom_components/frigate/diagnostics.py
  tests/test_diagnostics.py
Labels: enhancement

#255 Bump version to v2.3 .
  custom_components/frigate/manifest.json
Labels: build

#248 💥 Support for general motion sensor
  custom_components/frigate/__init__.py
  custom_components/frigate/binary_sensor.py
  tests/__init__.py
  tests/test_binary_sensor.py
  tests/test_init.py
Labels: enhancement, breaking

#263 Remove deprecated HACS manifest values
  hacs.json
Labels: build

#262 Ability to disable media browser
  custom_components/frigate/config_flow.py
  custom_components/frigate/const.py
  custom_components/frigate/media_source.py
  custom_components/frigate/translations/en.json
  tests/test_config_flow.py
  tests/test_media_source.py
Labels: enhancement

#267 Proxy the new Frigate recordings API (allows the card to support recordings)
  custom_components/frigate/__init__.py
  custom_components/frigate/views.py
  tests/test_views.py
Labels: enhancement
