Repository blakeblackshear/frigate-hass-integration, pull requests merged in 2022-12, with the labels that each got.

#380 Fix flake8 in the build
  .pre-commit-config.yaml
Labels: build

#381 Merge master back into the v0.12 branch
  .github/workflows/build.yaml
  .github/workflows/labeler.yml
  .github/workflows/release-drafter.yml
  .pre-commit-config.yaml
  README.md
Labels: build

#369 FEAT: Support sensors for per-process CPU usage
  custom_components/frigate/sensor.py
  tests/__init__.py
  tests/test_sensor.py
Labels: enhancement

#344 Add sensor for gpu usage
  custom_components/frigate/sensor.py
  tests/__init__.py
  tests/test_sensor.py
Labels: enhancement, pending

#385 Update build badge due to upstream breaking change
  README.md
Labels: documentation

#384 Support Frigate v0.12 UTC based recording paths
  custom_components/frigate/media_source.py
  tests/test_media_source.py
Labels: refactoring

#390 Bump version on v0.12 branch to match backend release
  custom_components/frigate/manifest.json
Labels: build

#386 [FEAT]: Birdseye Camera Entity with birdseye stream
  custom_components/frigate/camera.py
  tests/__init__.py
  tests/test_camera.py
Labels: enhancement
