Repository blakeblackshear/frigate-hass-integration, pull requests merged in 2022-06, with the labels that each got.

#274 Bump version to v3.0.0-rc.1
  custom_components/frigate/manifest.json
Labels: build

#276 Fix entity rename for unusually named entities
  custom_components/frigate/__init__.py
  custom_components/frigate/manifest.json
  tests/test_init.py
Labels: bug

#278 Add a server status sensor
  custom_components/frigate/__init__.py
  custom_components/frigate/const.py
  custom_components/frigate/sensor.py
  tests/__init__.py
  tests/test_sensor.py
Labels: enhancement

#271 Support built in motion detection read / set
  custom_components/frigate/__init__.py
  custom_components/frigate/binary_sensor.py
  custom_components/frigate/camera.py
  custom_components/frigate/sensor.py
  custom_components/frigate/switch.py
  tests/test_camera.py
Labels: enhancement

#284 Bump docker-compose forwarded ports
  docker-compose.yml
Labels: testing

#283 Set use_wallclock_as_timestamps stream option
  custom_components/frigate/camera.py
Labels: enhancement

#285 Rename the devcontainer Frigate camera
  .devcontainer/frigate.yml
Labels: testing

#287 Improve devcontainer environment
  .devcontainer/config/configuration.yaml
  .devcontainer/config/preconfig/.storage/frontend.user_data_1141ee80e0a647c1a4687d0b7631a019
  .devcontainer/config/preconfig/.storage/lovelace
  .devcontainer/config/preconfig/.storage/lovelace_resources
  .gitignore
  .vscode/launch.json
  docker-compose.yml
Labels: testing

#288 Improve devcontainer preconfig
  .devcontainer/devcontainer.json
  .devcontainer/preconfig.sh
  .devcontainer/preconfig/.storage/auth
  .devcontainer/preconfig/.storage/auth_provider.homeassistant
  .devcontainer/preconfig/.storage/core.config_entries
  .devcontainer/preconfig/.storage/frontend.user_data_1141ee80e0a647c1a4687d0b7631a019
  .devcontainer/preconfig/.storage/lovelace
  .devcontainer/preconfig/.storage/lovelace_resources
  .devcontainer/preconfig/.storage/onboarding
  docker-compose.yml
Labels: testing

#289 Allow setting specific HA/Frigate versions in devcontainer
  .devcontainer/config/configuration.yaml
  .env.example
  docker-compose.yml
Labels: testing

#290 Revert "Set use_wallclock_as_timestamps stream option"
  custom_components/frigate/camera.py
Labels: bug

#291 Prevent assert from cors library on preparing response to cors request
  custom_components/frigate/views.py
Labels: bug

#297 Add recordings WS endpoint
  custom_components/frigate/api.py
  custom_components/frigate/views.py
  custom_components/frigate/ws_api.py
  tests/test_api.py
  tests/test_ws_api.py
Labels: enhancement
