Repository blakeblackshear/frigate-hass-integration, pull requests merged in 2023-06, with the labels that each got.

#496 Add stalebot
  .github/workflows/stale.yml
Labels: build

#497 Bump max operations count for stalebot
  .github/workflows/stale.yml
Labels: build

#500 Merge recent small changes from `master` back into `dev`
  .github/workflows/build.yaml
  .github/workflows/stale.yml
Labels: build

#499 Add Russian language support
  custom_components/frigate/translations/ru.json
Labels: enhancement

#504 Don't mark certain labels as stale
  .github/workflows/stale.yml
Labels: build

#506 Ignore attribute labels
  custom_components/frigate/__init__.py
  custom_components/frigate/const.py
Labels: bug
