Repository blakeblackshear/frigate-hass-integration, pull requests merged in 2023-01, with the labels that each got.

#389 Rewrite recordings media source to use Recordings Summary API
  custom_components/frigate/api.py
  custom_components/frigate/manifest.json
  custom_components/frigate/media_source.py
  requirements.txt
  requirements_dev.txt
  tests/test_api.py
  tests/test_media_source.py
Labels: refactoring

#391 Add translations for RTSP template configuration option
  custom_components/frigate/translations/en.json
  custom_components/frigate/translations/pt-BR.json
  custom_components/frigate/translations/pt_br.json
Labels: documentation

#392 Switch to region-agnostic media browser title formats
  custom_components/frigate/media_source.py
  tests/test_media_source.py
Labels: enhancement

#398 Fix binary sensor classes
  custom_components/frigate/binary_sensor.py
Labels: refactoring

#397 Use the HA timezone setting for requesting recordings, provide timezone to event summary
  custom_components/frigate/__init__.py
  custom_components/frigate/api.py
  custom_components/frigate/manifest.json
  custom_components/frigate/media_source.py
  custom_components/frigate/ws_api.py
  requirements.txt
  requirements_dev.txt
  tests/test_api.py
  tests/test_media_source.py
  tests/test_ws_api.py
Labels: bug

#401 Bump to beta 2
  custom_components/frigate/manifest.json
Labels: build

#410 Expose timezone in `ws_api`
  custom_components/frigate/ws_api.py
  tests/test_ws_api.py
Labels: bug

#414 Update version for beta3
  custom_components/frigate/manifest.json
Labels: build

#415 `_attr_is_streaming` should respect go2rtc streams
  custom_components/frigate/camera.py
Labels: bug

#416 Change Frigate `api` and `ws_api` to multi selection instead of single selection
  custom_components/frigate/api.py
  custom_components/frigate/media_source.py
  custom_components/frigate/ws_api.py
  tests/test_api.py
  tests/test_media_source.py
  tests/test_ws_api.py
Labels: breaking, performance

#417 Latest version check: add handling for "disabled"
  custom_components/frigate/update.py
Labels: bug

#419 Force AAC audio to be used in RTSP URL
  custom_components/frigate/camera.py
  tests/test_camera.py
Labels: bug

#420 Allow searching for favorites via API
  custom_components/frigate/api.py
  custom_components/frigate/ws_api.py
  tests/test_ws_api.py
Labels: enhancement

#423 Update to beta4
  custom_components/frigate/manifest.json
Labels: build

#425 Bump `isort` to fix CI
  .pre-commit-config.yaml
Labels: build

#424 Merge master branch back into v0.12 branch
  .github/workflows/build.yaml
  .github/workflows/labeler.yml
  .github/workflows/release-drafter.yml
  .pre-commit-config.yaml
  README.md
  custom_components/frigate/update.py
Labels: build

#426 Fixes for Home Assistant 2023.1.7+, Python 3.9, Python 3.10
  custom_components/frigate/__init__.py
  custom_components/frigate/camera.py
  custom_components/frigate/media_source.py
  custom_components/frigate/views.py
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  tests/__init__.py
  tests/test_api.py
  tests/test_binary_sensor.py
  tests/test_camera.py
  tests/test_number.py
  tests/test_sensor.py
  tests/test_switch.py
  tests/test_update.py
Labels: build

#427 Merge updates for latest HomeAssistant
  custom_components/frigate/__init__.py
  custom_components/frigate/camera.py
  custom_components/frigate/views.py
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  tests/__init__.py
  tests/test_api.py
  tests/test_binary_sensor.py
  tests/test_camera.py
  tests/test_number.py
  tests/test_sensor.py
  tests/test_switch.py
  tests/test_update.py
Labels: build

#430 Fix handling of GPU error conditions in sensors
  custom_components/frigate/sensor.py
  tests/test_sensor.py
Labels: bug
