Repository blakeblackshear/frigate-hass-integration, pull requests merged in 2023-04, with the labels that each got.

#455 Update devcontainer versions
  docker-compose.yml
Labels: testing

#471 Update UI navigation path for HACS
  README.md
Labels: documentation

#478 Add `inlang` to make the contribution of translations easier
  custom_components/frigate/translations/de.json
  custom_components/frigate/translations/en.json
  custom_components/frigate/translations/pt-BR.json
  custom_components/frigate/translations/pt_br.json
  inlang.config.js
Labels: build

#480 Fix typo in docstring in `config_flow.py`
  custom_components/frigate/config_flow.py
Labels: bug
