Repository blakeblackshear/frigate-hass-integration, pull requests merged in 2023-10, with the labels that each got.

#557 Upgrade pylint/pylint-test and address variety of pylint issues
  custom_components/frigate/__init__.py
  custom_components/frigate/camera.py
  custom_components/frigate/config_flow.py
  custom_components/frigate/const.py
  custom_components/frigate/diagnostics.py
  custom_components/frigate/media_source.py
  custom_components/frigate/update.py
  pyproject.toml
  requirements_dev.txt
Labels: build

#556 Expose camera PTZ information over websocket
  custom_components/frigate/api.py
  custom_components/frigate/ws_api.py
  tests/test_api.py
  tests/test_ws_api.py
Labels: enhancement

#555 Adapt to upstream stats structure change for cameras
  custom_components/frigate/camera.py
  custom_components/frigate/const.py
  custom_components/frigate/sensor.py
  tests/__init__.py
  tests/test_camera.py
  tests/test_sensor.py
Labels: breaking

#553 Add WebRTC streaming to camera entities
  custom_components/frigate/camera.py
  custom_components/frigate/config_flow.py
  custom_components/frigate/const.py
  custom_components/frigate/translations/en.json
  tests/test_camera.py
  tests/test_config_flow.py
Labels: enhancement

#558 Update build to `5.0.0-beta.3`
  custom_components/frigate/manifest.json
Labels: build

#562 Upgrade pylint/pylint-test and address variety of pylint issues
  custom_components/frigate/__init__.py
  custom_components/frigate/camera.py
  custom_components/frigate/config_flow.py
  custom_components/frigate/const.py
  custom_components/frigate/diagnostics.py
  custom_components/frigate/media_source.py
  custom_components/frigate/update.py
  pyproject.toml
  requirements_dev.txt
Labels: build
