Repository blakeblackshear/frigate-hass-integration, pull requests merged in 2024-02, with the labels that each got.

#613 Fixed typo in german translation
  custom_components/frigate/translations/de.json
Labels: bug

#618 Fix 0.12 events media browser failure
  custom_components/frigate/media_source.py
Labels: bug

#622 Update version for release
  custom_components/frigate/manifest.json
Labels: build

#626 Fix media browsing bug with events where `top_score` is `0`
  custom_components/frigate/media_source.py
Labels: bug

#628 Merge recent `master` fixes back into `dev`
  custom_components/frigate/manifest.json
  custom_components/frigate/media_source.py
Labels: build

#635 Unpin pytz version in manifest requirement
  custom_components/frigate/manifest.json
Labels: build

#633 Add French translation
  custom_components/frigate/translations/fr.json
Labels: enhancement
