Repository blakeblackshear/frigate-hass-integration, pull requests merged in 2024-05, with the labels that each got.

#671 Fix HA incompatibility: always try to decode MQTT payloads
  custom_components/frigate/__init__.py
  custom_components/frigate/binary_sensor.py
  custom_components/frigate/camera.py
  custom_components/frigate/switch.py
  tests/test_switch.py
Labels: bug

#672 Bump version to v5.2.0 .
  custom_components/frigate/manifest.json
Labels: build

#673 Merged `dev` back into `master`
  custom_components/frigate/__init__.py
  custom_components/frigate/binary_sensor.py
  custom_components/frigate/camera.py
  custom_components/frigate/manifest.json
  custom_components/frigate/switch.py
  custom_components/frigate/translations/ca.json
  tests/test_switch.py
Labels: build

#664 Support proxy view for preview gifs
  custom_components/frigate/views.py
  tests/test_views.py
Labels: enhancement
