Repository blakeblackshear/frigate-hass-integration, pull requests merged in 2024-11, with the labels that each got.

#758 refactor: Move proxy fuctionality to a common library
  custom_components/frigate/manifest.json
  custom_components/frigate/views.py
  requirements.txt
  tests/test_views.py
Labels: refactoring

#775 fix: Fix `pt`/`pt-BR` translations
  custom_components/frigate/translations/pt.json
  custom_components/frigate/translations/pt_br.json
Labels: bug

#776 fix: Remove [old] `rtmp` support
  custom_components/frigate/__init__.py
  custom_components/frigate/camera.py
  custom_components/frigate/config_flow.py
  custom_components/frigate/const.py
  custom_components/frigate/translations/ca.json
  custom_components/frigate/translations/de.json
  custom_components/frigate/translations/en.json
  custom_components/frigate/translations/fr.json
  custom_components/frigate/translations/pt-BR.json
  custom_components/frigate/translations/pt.json
  custom_components/frigate/translations/ru.json
  info.md
  tests/__init__.py
  tests/test_camera.py
  tests/test_config_flow.py
  tests/test_init.py
Labels: bug

#779 chore: Bump `hass-web-proxy-lib` to `v0.0.7`
  custom_components/frigate/manifest.json
  requirements.txt
Labels: dependencies

#780 chore: Bump version to `v5.5.0`
  custom_components/frigate/manifest.json
Labels: build

#767 Add Active Count Sensor
  .devcontainer/set_dot_env.sh
  custom_components/frigate/sensor.py
  tests/__init__.py
  tests/test_sensor.py
Labels: enhancement

#783 Switch from pip to uv
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/post_create.sh
  .devcontainer/set_dot_env.sh
  .github/workflows/build.yaml
  .vscode/settings.json
  docker-compose.yml
Labels: build

#782 Correctly handle cameras that are not streaming
  custom_components/frigate/camera.py
  tests/test_camera.py
Labels: bug

#794 fix: Don't block on loading tzinfo objects
  custom_components/frigate/manifest.json
  custom_components/frigate/media_source.py
  requirements.txt
  requirements_dev.txt
  tests/test_media_source.py
Labels: bug
