Repository blakeblackshear/frigate-hass-integration, pull requests merged in 2025-05, with the labels that each got.

#869 Fix logos
  custom_components/frigate/__init__.py
  custom_components/frigate/binary_sensor.py
  custom_components/frigate/const.py
  custom_components/frigate/image.py
  custom_components/frigate/sensor.py
  tests/__init__.py
  tests/test_init.py
Labels: Stale

#894 Add sensors for face and license plate recognition
  custom_components/frigate/icons.py
  custom_components/frigate/sensor.py
  tests/__init__.py
  tests/test_sensor.py
Labels: enhancement

#895 Update version to 5.9.0
  custom_components/frigate/manifest.json
Labels: build

#897 Fix incorrect access of 0.16 only property
  custom_components/frigate/__init__.py
  custom_components/frigate/manifest.json
Labels: bug

#899 Fix handling of old Frigate version that used int type
  custom_components/frigate/__init__.py
  custom_components/frigate/camera.py
  custom_components/frigate/manifest.json
  custom_components/frigate/sensor.py
Labels: bug

#912 Improve disabled behavior
  custom_components/frigate/camera.py
Labels: enhancement

#914 camera: Make it correctly use auth headers for webrtc connections
  custom_components/frigate/camera.py
Labels: bug
